//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Admin
    {
        public int adminID { get; set; }
        [Display(Name = "Username")]
        public string username { get; set; }
        [Display(Name ="Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    }
}
