//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Attendance
    {
        public int attendanceID { get; set; }
        [Display(Name ="Student Name")]
        public int studentID { get; set; }
        [Display(Name = "Course Name")]
        public int courseID { get; set; }
        [Display(Name = "Attendance Percentage")]
        public string attendance_percentage { get; set; }
        [Display(Name = "Date")]
        public string date { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
