//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Attendances = new HashSet<Attendance>();
            this.CourseRegs = new HashSet<CourseReg>();
            this.LecturerRegs = new HashSet<LecturerReg>();
            this.PasswordTokens = new HashSet<PasswordToken>();
        }
    
        public int courseID { get; set; }

        [Display(Name ="Course Code")]
        public string course_code { get; set; }
        [Display(Name ="Course Title")]
        public string course_title { get; set; }
        [Display(Name ="Class Holds")]
        public int number_of_days { get; set; }
        public Nullable<int> passwordID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseReg> CourseRegs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturerReg> LecturerRegs { get; set; }
        public virtual PasswordToken PasswordToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordToken> PasswordTokens { get; set; }
    }
}
