//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturerReg
    {
        public int lecturer_regID { get; set; }
        public int courseID { get; set; }
        public int lecturerID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
